# Generated by Django 3.1.5 on 2021-02-02 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210203_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='cita',
        ),
    ]
