# Generated by Django 3.1.5 on 2021-02-02 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_remove_employee_cita'),
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.employee', verbose_name='Empleado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cita',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
