# Generated by Django 3.1.5 on 2021-02-03 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_auto_20210203_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='typeof',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='citas.tipocita', verbose_name='Tipo de cita'),
        ),
    ]
