# Generated by Django 3.1.5 on 2021-02-03 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0005_auto_20210203_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='typeof',
        ),
    ]
