# Generated by Django 3.1.5 on 2021-02-03 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0006_remove_cita_typeof'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='typeof',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='citas.tipocita', verbose_name='Tipo de cita'),
        ),
        migrations.AlterField(
            model_name='tipocita',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Nombre'),
        ),
    ]
