# Generated by Django 3.1.5 on 2021-02-10 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_auto_20210203_2309'),
        ('citas', '0002_auto_20210203_2307'),
        ('citas', '0008_auto_20210203_2303'),
        ('citas', '0002_auto_20210203_2314'),
        ('citas', '0002_auto_20210203_2318'),
    ]

    operations = [
    ]
