# Generated by Django 3.1.5 on 2021-02-13 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210211_1931'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('citas', '0009_merge_20210210_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='accepted',
            field=models.BooleanField(default=False, verbose_name='¿Aceptada?'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='employee',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.employee', verbose_name='Empleado'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='typeof',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='citas.tipocita', verbose_name='Tipo de cita'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
