# Generated by Django 3.1.5 on 2021-02-13 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0011_auto_20210214_0030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='coments',
        ),
        migrations.AddField(
            model_name='cita',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Comentario'),
        ),
    ]
